name: Generate xml sitemap

on:
  push:
    branches: [ main ]
    paths: [ '**.html', '**.pdf' ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: 'https://yunadata.github.io/'
        include-pdf: false
        # Exclude the private folder so it doesn't appear in the sitemap
        exclude-paths: |
          skanefusion/**

    - name: Commit and push
      run: |
        if [[ `git status --porcelain sitemap.xml` ]]; then
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add sitemap.xml
          git commit -m "Automated sitemap update"
          git push
        else
          echo "No changes to sitemap"
        fi
